### PR TITLE
Added simplerr.wrapErrorNoHalt

### PR DESCRIPTION
**Pull request by Bo98**
It's a fucking awful implementation but until https://github.com/Facepunch/garrysmod-requests/issues/668 is addressed, I don't think there's anything better.

### CODE REVIEW

**Comment by FPtje** [comment]
If it requires such a hack, then I'd rather people create their own error handlers that do not halt the execution.

**Comment by Bo98** [comment]
DarkRP.errorNoHalt doesn't even work without it though. Would you rather this be moved to DarkRP?

**Comment by FPtje** [comment]
Yes it does, it doesn't use ErrorNoHalt:

``` lua
DarkRP.errorNoHalt = fc{
    simplerr.wrapHook,
    simplerr.wrapLog,
    simplerr.runError,
    function(msg, err, ...) return msg, err and err + 3 or 4, ... end -- Raise error level one higher
}
```

**Comment by Bo98** [comment]
That doesn't work clientside though. It also does not display in the server console in either realm. The only thing it does is send the error to admins when run serverside.

**Comment by FPtje** [comment]
The fact that your PR exists doesn't suddenly break that function. The error may not appear in the Lua error logs, but showing it to the admins on join is good enough to me.

Throwing an error in a timer is not an acceptable solution. It can cause undefined behaviour with respect to other timers and maybe even the think hook.

**Comment by Bo98** [comment]
> It can cause undefined behaviour with respect to other timers and maybe even the think hook.

GMod handles this. The entire thing is handled in C++. But I do agree that it's not ideal. You can use Msg if you want. It does a better job than the current implementation of `DarkRP.errorNoHalt` but with the one disadvantage over this PR of losing the sending of errors from the client to the server.

> but showing it to the admins on join is good enough to me

Still doesn't take away from the uselessness when run clientside. It does not currently display for _anyone_ when run clientside.

**Comment by FPtje** [comment]
I now have this:

```
gamemodes/darkrp/gamemode/libraries/simplerr.lua:513: [ERROR] A runtime error has occurred in "lua/crashtest.lua" on line 6.
The best help I can give you is this:

bad input or some shit

Hints:
    - No hints, sorry.

The responsibility for this error lies with (the authors of) one (or more) of these files:
    1. lua/crashtest.lua on line 6
    2. function 'xpcall'
    3. gamemodes/darkrp/gamemode/libraries/simplerr.lua on line 464
    4. lua/crashtest.lua on line 10
    5. lua/crashtest.lua on line 2
    6. lua_run on line 1
------- End of Simplerr error -------
```

The outer `xpcall` and simplerr are gone, but the inner one is still there. I don't know why that one isn't removed too, so that's what I'm looking into now.

**Comment by FPtje** [comment]
Oh the inner error already contains both `xpcall` stack lines. In that case I guess it makes sense to leave the inner one in.

**Comment by Bo98** [comment]
LGTM but I don't know why you're posting in this PR.

**Comment by FPtje** [comment]
god damnit, wrong issue. I meant to post it in #5

**Comment by Bo98** [comment]
Is there something you have in mind about DarkRP.errorNoHalt clientside?

**Comment by FPtje** [comment]
I'm working on that now

**Pull request closed without merging**
